getFirstIndex<-function(year, lowerbound,upperbound)
            {
             index=1
             runningyear=lowerbound
             if(runningyear!=year)
              {
                   repeat
                         {
                          if(runningyear%%4==0)
                                              {
                                               index=index+366
                                               }
                          else
                                               {
                                                 index=index+365
                                               }
                          runningyear=runningyear+1
                          if(runningyear>upperbound)
                                                 {
                                                  stop("year can not be found in the current file")
                                                 }
                          if(runningyear==year)
                                                 {
                                                  break
                                                 }
                        }
                 }
             return(index)
           }
