k="rcp2p6"
source("SimBrazil_hadgem.r")
source("SimBrazil_noresm.r")
source("SimBrazil_ipsl.r")
source("SimBrazil_miroc.r")
source("SimBrazil_gfdl.r")
k="rcp4p5"
source("SimBrazil_hadgem.r")
source("SimBrazil_noresm.r")
source("SimBrazil_ipsl.r")
source("SimBrazil_miroc.r")
source("SimBrazil_gfdl.r")
k="rcp6p0"
source("SimBrazil_hadgem.r")
source("SimBrazil_noresm.r")
source("SimBrazil_ipsl.r")
source("SimBrazil_miroc.r")
source("SimBrazil_gfdl.r")
k="rcp8p5"
source("SimBrazil_hadgem.r")
source("SimBrazil_noresm.r")
source("SimBrazil_ipsl.r")
source("SimBrazil_miroc.r")
source("SimBrazil_gfdl.r")
